CREATE USER USER01 IDENTIFIED BY USER01
DEFAULT TABLESPACE USERS;

GRANT CONNECT, RESOURCE, DBA TO USER01;

COMMIT;


CREATE USER MANAGER01 IDENTIFIED BY MANAGER01
DEFAULT TABLESPACE USERS;

GRANT CONNECT, RESOURCE, DBA TO MANAGER01;

COMMIT;

CREATE USER USER22 IDENTIFIED BY USER22
DEFAULT TABLESPACE USERS;

GRANT CONNECT, RESOURCE, DBA TO USER22; 