-- 이름, 전화번호, 이메일, 나이
CREATE TABLE TEST(
	NAME VARCHAR(100),
	P_NUMBER VARCHAR(13),
	EMAIL VARCHAR(100),
	AGE NUMBER(3)
);

INSERT INTO TEST (NAME, P_NUMBER, EMAIL, AGE) 
SELECT 'A', '010-1111-1111', 'A1@gmail.com', 15 FROM DUAL UNION ALL
SELECT 'B', '010-2222-2222', 'B1@gmail.com', 17 FROM DUAL;

INSERT INTO TEST (NAME, P_NUMBER, EMAIL, AGE) VALUES ('A', '010-1111-1111', 'A1@gmail.com', 15);
INSERT INTO TEST (NAME, P_NUMBER, EMAIL, AGE) VALUES ('B', '010-2222-2222', 'B1@gmail.com', 15);

SELECT * FROM TEST;

DROP TABLE TEST;


-- 이름 id pw 전화번호 이메일 나이

-- 1. COLUMN 레벨 방식

CREATE TABLE MEMBER(
	ID VARCHAR2(50) CONSTRAINT MEMBER_ID_PK PRIMARY KEY,
	PW VARCHAR2(50) CONSTRAINT MEMBER_PW_NN NOT NULL,
	NAME VARCHAR2(50),
	PHONE VARCHAR2(50) CONSTRAINT MEMBER_PHONE_U UNIQUE,
	EMAIL VARCHAR2(100) CONSTRAINT MEMBER_EMAIL_U UNIQUE,
	AGE NUMBER(3) CHECK (AGE BETWEEN 0 AND 150)
);

-- 2. TABLE 방식
CREATE TABLE MEMBER(
	ID VARCHAR2(50),
	PW VARCHAR2(50),
	NAME VARCHAR2(50),
	PHONE VARCHAR2(50),
	EMAIL VARCHAR2(100),
	AGE NUMBER(3),
	CONSTRAINT MEMBER_ID_PK PRIMARY KEY (ID),
	CONSTRAINT MEMBER_PHONE_U UNIQUE (PHONE)
);

CREATE TABLE BOARD (
	NUM NUMBER CONSTRAINT BOARD_NUM_PK PRIMARY KEY,
	TITLE VARCHAR2(200),
	CONTENTS CLOB,
	WRITER VARCHAR2(50), --CONSTRAINT BOARD_W_FK REFERENCES MEMBER (ID),
	REGDATE DATE,
	HIT NUMBER
	--CONSTRAINT BOARD_W_FK FOREIGN KEY (WRITER) REFERENCES MEMBER (ID)
);

SELECT * FROM BOARD;

INSERT INTO MEMBER (ID, PW, NAME, PHONE, EMAIL, AGE) VALUES ('W1', 'TEST', 'TEST', '0101111', 'TEST@gmail.com', 30);

INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'T1', 'C1', 'W1', SYSDATE, 0);

SELECT * FROM MEMBER;

DELETE MEMBER WHERE ID = 'W1';


INSERT INTO MEMBER (ID, PW, NAME, PHONE, EMAIL, AGE) VALUES ('TEST', 'TEST', 'TEST', '0101114', NULL, 30);

INSERT INTO MEMBER (ID, PW, NAME, PHONE, EMAIL, AGE) VALUES ('TEST1', 'TEST', 'TEST', '0101112', NULL, 20);

INSERT INTO MEMBER (ID, PW, NAME, PHONE, EMAIL, AGE) VALUES ('TEST2', 'TEST', 'TEST', '0101113', NULL, 30);

SELECT * FROM MEMBER;

SELECT * FROM USER_CONSTRAINTS;

DROP TABLE MEMBER;
DROP TABLE BOARD;

CREATE TABLE ADDRESS(
	NUM NUMBER CONSTRAINT ADD_NUM_NN NOT NULL,
	NAME VARCHAR(100) CONSTRAINT ADD_NAME_NN NOT NULL,
	PHONE VARCHAR(20) NULL,
	EMAIL VARCHAR(200) NULL
);

DROP TABLE ADDRESS;

INSERT INTO ADDRESS VALUES(1, 'TEST', '011', 'GMAIL');

FLASHBACK TABLE MEMBER TO BEFORE DROP;
SELECT * FROM RECYCLEBIN;
PURGE RECYCLEBIN;

------------------------
ALTER TABLE MEMBER ADD (BIRTH VARCHAR(11));

ALTER TABLE "MEMBER" DROP COLUMN BIRTH;

ALTER TABLE "MEMBER" RENAME COLUMN "ID" TO "USER_NAME";

UPDATE "MEMBER" SET PHONE = NULL;

ALTER TABLE "MEMBER" MODIFY (PHONE NUMBER);

ALTER TABLE "MEMBER" DROP CONSTRAINT MEMBER_PHONE_U;

ALTER TABLE "BOARD" ADD CONSTRAINT BOARD_WR_FK FOREIGN KEY (WRITER) REFERENCES MEMBER (ID); 

CREATE SEQUENCE BOARD_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOMINVALUE
NOCYCLE
NOCACHE;

SELECT * FROM SEQ;

SELECT BOARD_SEQ.CURRVAL FROM DUAL;


CREATE TABLE PRODUCT (
	NUM NUMBER,
	P_NAME VARCHAR(500),
	P_EX CLOB,
	RATE NUMBER(2),
	TAG CLOB
);

CREATE TABLE P_OPTION(
	OP_NAME VARCHAR(100),
	OP_PRICE NUMBER,
	OP_STOCK NUMBER
);















