CREATE TABLE ROLE(
	ROLE_NUM NUMBER CONSTRAINT ROLE_NUM_PK PRIMARY KEY,
	ROLE_NAME VARCHAR2(100)
);

CREATE TABLE MEMBER(
	ID VARCHAR(50) CONSTRAINT MEMBER_ID_PK PRIMARY KEY,
	PW VARCHAR(100),
	NAME VARCHAR(50),
	ADDRESS VARCHAR(200),
	PHONE VARCHAR(20),
	EMAIL VARCHAR(100)
);


CREATE TABLE ADDRESS(
	AD_NUM NUMBER CONSTRAINT ADDRESS_NUM_PK PRIMARY KEY,
	ID VARCHAR(50) CONSTRAINT ADDRESS_ID_FK REFERENCES MEMBER (ID),
	ADDRESS VARCHAR(200),
	PHONE VARCHAR(20),
	AD_NAME VARCHAR(200)
);


CREATE TABLE PRODUCT(
	PRO_NUM NUMBER CONSTRAINT PRODUCT_NUM_PK PRIMARY KEY,
	PRO_INTRODUCE VARCHAR(200),
	RATING NUMBER,
	TAG CLOB,
	PRO_NAME VARCHAR(200)
);


CREATE TABLE PRODUCTOPTION(
	OPTION_NUM NUMBER CONSTRAINT PRODUCTOPTION_NUM_PK PRIMARY KEY,
	PRO_NUM NUMBER CONSTRAINT PRODUCTOPTION_PNUM_FK REFERENCES PRODUCT (PRO_NUM),
	OPTION_NAME VARCHAR(200),
	OPTION_PRICE NUMBER,
	OPTION_STOCK NUMBER
);


CREATE TABLE TAG(
	TAG_NUM NUMBER CONSTRAINT COMMENT_TNUM_PK PRIMARY KEY,
	PRO_NUM NUMBER CONSTRAINT COMMENT_PNUM_FK REFERENCES PRODUCT (PRO_NUM),
	ID VARCHAR(50) CONSTRAINT COMMENT_ID_FK REFERENCES MEMBER (ID),
	TAG_DATE DATE,
	RATING NUMBER,
	TAG_CONTENTS CLOB
);


CREATE TABLE BUCKET(
	BUCKET_NUM NUMBER CONSTRAINT BUCKET_NUM_PK PRIMARY KEY,
	ID VARCHAR(50) CONSTRAINT BUCKET_ID_FK REFERENCES MEMBER(ID),
	PRO_NAME VARCHAR(200),
	PRO_NUM NUMBER CONSTRAINT BUCKET_PRO_NUM_FK REFERENCES PRODUCT(PRO_NUM),
	BUCKET_COUNT NUMBER CONSTRAINT BUCEKT_COUNT_NN NOT NULL,
	TOTAL_PRICE NUMBER,
	DISCOUNT_PRICE NUMBER
);

CREATE TABLE MEMBER_ROLE(
	ID VARCHAR2(200),
	ROLE_NUM NUMBER
);

--ALTER TABLE MEMBER_ROLE ADD CONSTRAINT MR_ID_FK FOREIGN KEY (ID) REFERENCES MEMBER (ID);
--ALTER TABLE MEMBER_ROLE ADD CONSTRAINT MR_RN_FK FOREIGN KEY (ROLE_NUM) REFERENCES ROLE;

ALTER TABLE MEMBER_ROLE ADD CONSTRAINT MR_PK PRIMARY KEY (ID, ROLE_NUM);




CREATE SEQUENCE ADDRESS_NUM_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE PRODUCT_NUM_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE TAG_NUM_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE OPTION_NUM_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE ROLE_NUM_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE BUCKET_NUM_SEQ
START WITH 1
INCREMENT BY 1;



DROP TABLE BUCKET;
DROP TABLE TAG;
DROP TABLE PRODUCTOPTION;
DROP TABLE PRODUCT;
DROP TABLE ADDRESS;
DROP TABLE MEMBER_ROLE;
DROP TABLE MEMBER;
DROP TABLE ROLE;



INSERT INTO ROLE (ROLE_NUM, ROLE_NAME) VALUES (ROLE_NUM_SEQ.NEXTVAL, '관리자');
INSERT INTO ROLE (ROLE_NUM, ROLE_NAME) VALUES (ROLE_NUM_SEQ.NEXTVAL, '매니저');
INSERT INTO ROLE (ROLE_NUM, ROLE_NAME) VALUES (ROLE_NUM_SEQ.NEXTVAL, '사용자');

SELECT * FROM ROLE;


INSERT INTO MEMBER (ID, PW,  NAME, ADDRESS, PHONE, EMAIL) VALUES ('T1', 'T1', 'T1', 'TEST ADDRESS1', 'TEST PHONE', 'TEST EMAIL');
INSERT INTO MEMBER (ID, PW,  NAME, ADDRESS, PHONE, EMAIL) VALUES ('T2', 'T2', 'T2', 'TEST ADDRESS2', 'TEST PHONE', 'TEST EMAIL');
INSERT INTO MEMBER (ID, PW,  NAME, ADDRESS, PHONE, EMAIL) VALUES ('T3', 'T3', 'T3', 'TEST ADDRESS3', 'TEST PHONE', 'TEST EMAIL');

SELECT * FROM MEMBER;


INSERT INTO MEMBER_ROLE VALUES('T1', 1);
INSERT INTO MEMBER_ROLE VALUES('T1', 2);
INSERT INTO MEMBER_ROLE VALUES('T2', 2);

SELECT * FROM MEMBER_ROLE;


INSERT INTO ADDRESS (AD_NUM, ID, ADDRESS, PHONE, AD_NAME) VALUES (ADDRESS_NUM_SEQ.NEXTVAL , 'T1', 'TEST ADDRESS1', 'TEST PHONE' , '집');
INSERT INTO ADDRESS (AD_NUM, ID, ADDRESS, PHONE, AD_NAME) VALUES (ADDRESS_NUM_SEQ.NEXTVAL , 'T2', 'TEST ADDRESS2', 'TEST PHONE' , '집');
INSERT INTO ADDRESS (AD_NUM, ID, ADDRESS, PHONE, AD_NAME) VALUES (ADDRESS_NUM_SEQ.NEXTVAL , 'T3', 'TEST ADDRESS3', 'TEST PHONE' , '집');

SELECT * FROM ADDRESS;


INSERT INTO PRODUCT (PRO_NUM, PRO_INTRODUCE, RATING, TAG, PRO_NAME) VALUES (PRODUCT_NUM_SEQ.NEXTVAL, 'ABC1', 3.2, 'ABC1', '상품1');
INSERT INTO PRODUCT (PRO_NUM, PRO_INTRODUCE, RATING, TAG, PRO_NAME) VALUES (PRODUCT_NUM_SEQ.NEXTVAL, 'ABC2', 3.7, 'ABC2', '상품2');
INSERT INTO PRODUCT (PRO_NUM, PRO_INTRODUCE, RATING, TAG, PRO_NAME) VALUES (PRODUCT_NUM_SEQ.NEXTVAL, 'ABC3', 4.1, 'ABC3', '상품3');

SELECT * FROM PRODUCT;


INSERT INTO PRODUCTOPTION (OPTION_NUM, PRO_NUM, OPTION_NAME, OPTION_PRICE, OPTION_STOCK) VALUES (PRODUCTOPTION_SEQ.NEXTVAL, 1,'상품1', 10000, 50);
INSERT INTO PRODUCTOPTION (OPTION_NUM, PRO_NUM, OPTION_NAME, OPTION_PRICE, OPTION_STOCK) VALUES (PRODUCTOPTION_SEQ.NEXTVAL, 2,'상품2', 20000, 50);
INSERT INTO PRODUCTOPTION (OPTION_NUM, PRO_NUM, OPTION_NAME, OPTION_PRICE, OPTION_STOCK) VALUES (PRODUCTOPTION_SEQ.NEXTVAL, 3,'상품3', 30000, 50);

SELECT * FROM PRODUCTOPTION;


INSERT INTO TAG (TAG_NUM, PRO_NUM, ID, TAG_DATE, RATING, TAG_CONTENTS) VALUES (TAG_NUM_SEQ.NEXTVAL, 1, 'T1', SYSDATE, 3.2, '???');
INSERT INTO TAG (TAG_NUM, PRO_NUM, ID, TAG_DATE, RATING, TAG_CONTENTS) VALUES (TAG_NUM_SEQ.NEXTVAL, 1, 'T2', SYSDATE, 4.2, '???');
INSERT INTO TAG (TAG_NUM, PRO_NUM, ID, TAG_DATE, RATING, TAG_CONTENTS) VALUES (TAG_NUM_SEQ.NEXTVAL, 1, 'T3', SYSDATE, 1.0, '???');

SELECT * FROM TAG;


INSERT INTO BUCKET (BUCKET_NUM, PRO_NUM, PRO_NAME, BUCKET_COUNT, DISCOUNT_PRICE, TOTAL_PRICE) VALUES (BUCKET_NUM_SEQ.NEXTVAL, 1, '상품1', 1, 0, 10000);
INSERT INTO BUCKET (BUCKET_NUM, PRO_NUM, PRO_NAME, BUCKET_COUNT, DISCOUNT_PRICE, TOTAL_PRICE) VALUES (BUCKET_NUM_SEQ.NEXTVAL, 1, '상품2', 1, 0, 20000);
INSERT INTO BUCKET (BUCKET_NUM, PRO_NUM, PRO_NAME, BUCKET_COUNT, DISCOUNT_PRICE, TOTAL_PRICE) VALUES (BUCKET_NUM_SEQ.NEXTVAL, 1, '상품3', 1, 0, 30000);

SELECT * FROM BUCKET;























